<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_SecondBlock" Id="{5b1a58fd-6131-41bc-aa58-fd0a19d2321e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SecondBlock EXTENDS FB_MyBlock
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>