<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="RegularFunction" Id="{f80a8020-3966-4dae-a6c7-7aceb360dfeb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION RegularFunction : LREAL
VAR_INPUT
    input       : LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[RegularFunction := input * 2.0;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>