#
# Test the source for Black reformatting (pass/fail)
#

name: Linting

on: push

jobs:

 flake8-black-lint:
    runs-on: ubuntu-latest
    name: Flake8 code check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: py-actions/flake8@v2
        with:
          path: "./src"
          plugins: "flake8-bugbear flake8-black"
