#
# This workflow will install the package and run the unittests.
#

name: Python application

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:

    name: Pytest ${{ matrix.python-version }}, ${{matrix.os}}

    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10"]
        include:
          - os: "windows-latest"
            python-version: "3.10"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt && pip install -r requirements-dev.txt
    - name: Patch files
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          cd tests/plc_code/extern/lcls-twincat-general/LCLSGeneral/LCLSGeneral && \
            sed -i 's/ST_FbDiagnostics/ST_fbDiagnostics/g' LCLSGeneral.plcproj && \
            sed -i 's/FB_TimeStampBuffer/FB_TimestampBuffer/g' LCLSGeneral.plcproj && \
            sed -i 's/FB_TimestampBufferGlobal/FB_TimeStampBufferGlobal/g' LCLSGeneral.plcproj
        fi
      shell: bash
    - name: Test with pytest
      run: |
        pytest ./tests
