#
# This workflow will install the package and run the unittests.
#

name: PyTest tests

on: push

permissions:
  contents: read

jobs:
  build:

    name: Pytest ${{ matrix.python-version }}, ${{matrix.os}}

    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10"]
        include:
          - os: "windows-latest"
            python-version: "3.10"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Test with pytest
      run: |
        pytest --cov=src/ --cov-report=term
    - name: Upload coverage reports to Codecov
      if: ${{matrix.python-version}} == '3.10' && ${{matrix.os}} == 'ubuntu-latest'
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
